export const ROUTE_CONSTANTS = {
  HOME: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  HELP: '/help',
  NEWS: '/news',
  NEWS_POST: '/news/:newsId',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  REPORTS: '/reports',
  REPORT: '/reports/:reportId',
  CONFERENCES: '/conferences',
  CONFERENCES_ADMIN: '/conferences/admin',
  CONFERENCE: '/conferences/:conferenceId',
  USERS: '/users',
  USER: '/users/:userId',
  SETTINGS: '/settings',
  NOT_FOUND: '/404',
};
