export const ROUTE_CONSTANTS = {
  HOME: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  HELP: '/help',
  NEWS: '/news',
  NEWS_POST: '/news/:newsId',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  REPORTS: '/reports',
  REPORT: '/report/:reportId',
  CONFERENCES: '/conferences',
  CONFERENCE: '/conference/:conferenceId',
  USERS: '/users',
  USER: '/user/:userId',
  SETTINGS: '/settings',
  NOT_FOUND: '/404',
};
