export const ROUTE_CONSTANTS = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  NEWS: '/news',
  DASHBOARD: '/dashboard',
  REPORTS: '/reports',
  REPORT: '/report/:reportId',
  CONFERENCES: '/conferences',
  CONFERENCE: '/conference/:conferenceId',
  USERS: '/users',
  USER: '/user/:userId',
  SETTINGS: '/settings',
  NOT_FOUND: '/404',
};
